branch-defaults:
  master:
    environment: talkapy
    group_suffix: null
global:
  application_name: talk
  default_ec2_keyname: talkapy
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
